name: HardCore
author: GamerDuck123
main: com.hardcore.HardCoreMain
version: 0.0.1-beta
api-version: 1.17
softdepend: [Vault]
description: >
             A plugin that turns hardcore mode up to 11